title: Stefan Kert - Software Engineering
email: stefan.kert@sbg.at
description: Website and Blog 
baseurl: ""
url: "" 
twitter_username: stefankert
github_username:  stefankert

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
contenturl: "/blog/content/"
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
